name: Deploy to Azure VPS

on:
  push:
    branches:
      - main
      - wethar-climate-dashbord

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            cd /var/www/lms
            git reset --hard HEAD
            git pull origin wethar-climate-dashbord
            cd /var/www/lms/admin && npm install && npm run build
            cd /var/www/lms/server && npm install && npm run build
            pm2 restart wcs-api || pm2 restart all
            echo "🚀 Deployment completed successfully!"
