name: Deploy to Azure VPS

on:
  push:
    branches:
      - main
      - wethar-climate-dashbord # triggers on your working branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /var/www/lms
            git pull origin $(git rev-parse --abbrev-ref HEAD)

            # Build Client
            cd /var/www/lms/client
            npm install
            npm run build

            # Build Admin
            cd /var/www/lms/admin
            npm install
            npm run build

            # Restart Backend Server
            cd /var/www/lms/server
            npm install
            npm run build
            pm2 restart wcs-api || pm2 restart all

            echo "🚀 Deployment completed successfully!"
